#------------------------------------------------------------------------------#
# Task --------------------------------------------------------------------
#------------------------------------------------------------------------------#

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


#------------------------------------------------------------------------------#
# Library -----------------------------------------------------------------
#------------------------------------------------------------------------------#

library(rbenchmark)
library(stats)

#------------------------------------------------------------------------------#
# Functions ---------------------------------------------------------------
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Code -------------------------------------------------------------------
#------------------------------------------------------------------------------#

fibo <- function(n){
  if (n < 2){
    return(n)
  }

  
  if (n == 2){
    return(1)
  }
  
  f <- 1:n; f[1] <- 1; f[2] <- 1;
  
  if (n > 2){
    for (i in 3:n){
      f[i] <- f[i-1] + f[i-2]
    }
    return(f[n])
  }
}
  # nxt <- prev1 + prev2
fibo(10)


n = 200
fl <- data.frame()
for (i in 1:n){
  fl <- rbind(fl, fibo(i))
}
fl$index <- seq(1:n)
colnames(fl) <- c("Fibs","Index")
fl

modl <- lm(Fibs ~ Index, data = fl)

predFibs <- data.frame(Index = c(3,4,5))

predict(modl, newdata = predFibs)


# Load the data
data("cars", package = "datasets")
# Build the model
model <- lm(dist ~ speed, data = cars)
model

new.speeds <- data.frame(
  speed = c(12, 19, 24)
)

predict(model, newdata = new.speeds)
